import React, { useRef, useState,  } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useDatabase } from "../../context/DatabaseContext";
import {
  LogOut,
  Clock,
  CheckCircle2,
  User,
  ExternalLink,
  Camera,
  Save,
  Edit3,
  X,
  Twitter,
  Linkedin,
  Phone,
  Mail,
  FileText,
  Briefcase,
  Link, // <-- Added Link icon for the share button
} from "lucide-react";

import Card from "../../components/shared/Card";
import SkillBadge from "../../components/shared/SkillBadge";
import PerformanceBadge from "../../components/shared/PerformanceBadge";
import EmptyState from "../../components/shared/EmptyState";

const formatUrl = (url) => {
  if (!url) return "";
  return url.startsWith("http://") || url.startsWith("https://")
    ? url
    : `https://${url}`;
};

export default function StudentDashboard() {
  const { courseKey, id } = useParams();
  const navigate = useNavigate();
  const { db, updateStudentProfile } = useDatabase();
  const fileInputRef = useRef(null);

  const course = db.courses[courseKey];
  const student = course?.students.find((s) => s.id === id);

  const [bio, setBio] = useState(student?.bio || "");
  const [isSavingBio, setIsSavingBio] = useState(false);
  const [isImageModalOpen, setIsImageModalOpen] = useState(false);
  const [isEditingSocials, setIsEditingSocials] = useState(false);
  const [copied, setCopied] = useState(false); // <-- Added copy state

  const [socials, setSocials] = useState({
    email: student?.email || "",
    whatsapp: student?.phone || "",
    twitter: student?.socialHandles?.twitter || "",
    linkedin: student?.socialHandles?.linkedin || "",
  });

  if (!student) {
    return (
      <div className="p-8 max-w-3xl mx-auto pt-20 min-h-screen">
        <EmptyState
          icon={User}
          title="Account Not Found"
          message="We could not locate your student records. Please log in again."
          actionButton={
            <button
              onClick={() => navigate("/")}
              className="bg-emerald-600 px-6 py-2.5 rounded-xl text-white font-bold"
            >
              Return to Login
            </button>
          }
        />
      </div>
    );
  }

  const isGraded = student.finalPerformanceScore !== null;

  // <-- Added handleCopyLink function
  const handleCopyLink = () => {
    const publicUrl = `${window.location.origin}/public/${courseKey}/${student.id}`;
    navigator.clipboard.writeText(publicUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleImageUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        updateStudentProfile(courseKey, student.id, { avatar: reader.result });
      };
      reader.readAsDataURL(file);
    }
  };

  const handleBioSave = () => {
    setIsSavingBio(true);
    updateStudentProfile(courseKey, student.id, { bio: bio });
    setTimeout(() => setIsSavingBio(false), 500);
  };

  const handleSaveSocials = () => {
    updateStudentProfile(courseKey, student.id, {
      email: socials.email,
      phone: socials.whatsapp,
      socialHandles: {
        ...(student.socialHandles || {}),
        twitter: socials.twitter,
        linkedin: socials.linkedin,
      },
    });
    setIsEditingSocials(false);
  };

  const handleDownloadCV = () => {
    const cvContent = `
=========================================
 PROFESSIONAL CURRICULUM VITAE
=========================================

Name: ${student.name}
Email: ${student.email || "Not Provided"}
WhatsApp: ${student.phone || "Not Provided"}
LinkedIn: ${student.socialHandles?.linkedin || "Not Provided"}
Twitter: ${student.socialHandles?.twitter || "Not Provided"}
GitHub: @${student.githubUsername}

Calculated Experience: ${student.yearsOfExperience || "0"} Years

-----------------------------------------
PROFESSIONAL SUMMARY:
-----------------------------------------
${bio || student.bio || "No summary provided."}

-----------------------------------------
TECHNICAL SKILLS:
-----------------------------------------
${student.skills?.join(", ") || "No skills listed."}

-----------------------------------------
ASSESSMENT SCORES:
-----------------------------------------
${
  isGraded
    ? `
Exam Score: ${student.examScore}/100
Projects: ${student.assignmentScore}/100
Soft Skills: ${student.behaviorScore}/100
FINAL PERFORMANCE RATING: ${student.finalPerformanceScore}
`
    : "Assessments currently under review by Hub Managers."
}

*** Document Auto-Generated by TalentOS ***
    `.trim();

    const blob = new Blob([cvContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${student.name.replace(/\s+/g, "_")}_TalentOS_CV.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 md:p-8 max-w-6xl mx-auto space-y-8 min-h-screen">
      {/* Image Modal Overlay */}
      {isImageModalOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4 animate-in fade-in"
          onClick={() => setIsImageModalOpen(false)}
        >
          <div
            className="relative max-w-2xl w-full flex justify-center"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setIsImageModalOpen(false)}
              className="absolute -top-12 right-0 md:-right-12 text-slate-400 hover:text-white transition"
            >
              <X className="w-8 h-8" />
            </button>
            <img
              src={student.avatar}
              alt="Profile Enlarged"
              className="w-full h-auto max-h-[85vh] object-cover object-center rounded-2xl shadow-2xl border border-slate-800"
            />
          </div>
        </div>
      )}

      {/* --- NEW DYNAMIC HEADER SECTION --- */}
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 border-b border-slate-800/50 pb-6 mb-8">
        {/* Left Side: Dynamic Greeting */}
        <div>
          {student.isNew ? (
            <>
              <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-2 tracking-tight">
                Your Workspace, {student.name.split(" ")[0]} 🚀
              </h1>
              <p className="text-slate-400 font-medium text-lg">
                Setup your profile to get discovered.
              </p>
            </>
          ) : (
            <>
              <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-2 tracking-tight">
                Welcome back, {student.name.split(" ")[0]}
              </h1>
              <p className="text-indigo-400 font-medium text-lg flex items-center gap-2 mt-1">
                Keep building.{" "}
                <span className="text-slate-500 text-sm font-normal px-2 border-l border-slate-700">
                  {course.name}
                </span>
              </p>
            </>
          )}
        </div>

        {/* Right Side: Badges & Actions */}
        <div className="flex items-center gap-3 bg-slate-900/50 p-1.5 rounded-xl border border-slate-800/50 backdrop-blur-sm w-fit h-fit">
          {/* Live Status Badge */}
          <div className="flex items-center gap-2 px-3 py-2 bg-slate-950 rounded-lg border border-slate-800 shadow-inner hidden sm:flex">
            <span className="relative flex h-2.5 w-2.5">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-500"></span>
            </span>
            <span className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              Profile Live
            </span>
          </div>

          {/* Share Profile Button */}
          <button
            onClick={handleCopyLink}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-bold transition-all duration-300 ${
              copied
                ? "bg-emerald-500 text-slate-950 shadow-[0_0_15px_rgba(16,185,129,0.4)]"
                : "bg-indigo-600 text-white hover:bg-indigo-500 shadow-lg shadow-indigo-500/20"
            }`}
          >
            {copied ? (
              <>
                <CheckCircle2 className="w-4 h-4" /> Copied!
              </>
            ) : (
              <>
                <Link className="w-4 h-4" /> Share Link
              </>
            )}
          </button>
        </div>
      </div>
      {/* --- END DYNAMIC HEADER SECTION --- */}

      <div className="grid lg:grid-cols-3 gap-8">
        {/* Left Column: Identity & Customization */}
        <div className="lg:col-span-1 space-y-6">
          <Card className="p-6 flex flex-col items-center text-center">
            <div className="relative group mb-4">
              <img
                src={student.avatar}
                alt="Profile"
                onClick={() => setIsImageModalOpen(true)}
                className="w-32 h-32 rounded-full border-4 border-slate-700 object-cover object-center shadow-xl group-hover:border-emerald-500/50 transition-colors cursor-pointer"
                title="Click to view full image"
              />
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  fileInputRef.current.click();
                }}
                className="absolute bottom-0 right-0 bg-emerald-500 hover:bg-emerald-400 p-2.5 rounded-full text-white transition shadow-[0_0_15px_rgba(16,185,129,0.5)] hover:scale-110"
                title="Change Profile Picture"
              >
                <Camera className="w-5 h-5" />
              </button>
              <input
                type="file"
                ref={fileInputRef}
                onChange={handleImageUpload}
                accept="image/*"
                className="hidden"
              />
            </div>

            <h2 className="text-xl font-bold text-white mb-1">
              {student.name}
            </h2>
            <p className="text-slate-400 font-mono text-sm mb-4 bg-slate-950 px-3 py-1 rounded-md border border-slate-800">
              ID: {student.academyId}
            </p>

            <div className="flex items-center gap-2 px-4 py-2 bg-indigo-500/10 border border-indigo-500/20 rounded-full mb-6">
              <Briefcase className="w-4 h-4 text-indigo-400" />
              <span className="text-xs font-bold text-indigo-300 uppercase">
                {student.yearsOfExperience} Years Experience
              </span>
            </div>

            <div className="w-full text-left space-y-4 pt-6 border-t border-slate-800/50">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                Your Skills
              </h3>
              <div className="flex flex-wrap gap-2">
                {student.skills?.map((skill) => (
                  <SkillBadge key={skill} skill={skill} />
                ))}
              </div>
            </div>
          </Card>

          <button
            onClick={handleDownloadCV}
            className="w-full flex items-center justify-center gap-2 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-white font-bold py-3.5 px-6 rounded-xl transition active:scale-95"
          >
            <FileText className="w-5 h-5 text-indigo-400" /> Download
            Professional CV
          </button>

          {isGraded && (
            <button
              onClick={() =>
                navigate(`/public/student/${courseKey}/${student.id}`)
              }
              className="w-full flex items-center justify-center gap-2 bg-indigo-600/10 hover:bg-indigo-600/20 border border-indigo-500/30 text-indigo-400 font-bold py-3.5 px-6 rounded-xl transition"
            >
              <ExternalLink className="w-5 h-5" /> View Public Profile
            </button>
          )}
        </div>

        {/* Right Column: Editing & Assessments */}
        <div className="lg:col-span-2 space-y-6">
          <Card className="p-6 md:p-8">
            <div className="flex items-center justify-between mb-4 border-b border-slate-800/50 pb-4">
              <div className="flex items-center gap-2">
                <Edit3 className="w-5 h-5 text-emerald-500" />
                <h2 className="text-xl font-bold text-white">
                  Professional Bio
                </h2>
              </div>
            </div>
            <p className="text-sm text-slate-400 mb-4">
              Update your summary. This is the first thing recruiters will read
              on your public portfolio.
            </p>
            <div className="space-y-4">
              <textarea
                value={bio}
                onChange={(e) => setBio(e.target.value)}
                rows="4"
                className="w-full bg-slate-900 border border-slate-700 text-white rounded-xl p-4 outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 transition resize-none leading-relaxed"
                placeholder="Write a brief professional summary about yourself..."
              />
              <div className="flex justify-end">
                <button
                  onClick={handleBioSave}
                  disabled={isSavingBio || bio === student.bio}
                  className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-500 disabled:bg-slate-800 disabled:text-slate-500 text-white font-bold py-2.5 px-6 rounded-xl transition active:scale-95"
                >
                  <Save className="w-4 h-4" />{" "}
                  {isSavingBio ? "Saving..." : "Save Changes"}
                </button>
              </div>
            </div>
          </Card>

          <Card className="p-6 md:p-8">
            <div className="flex justify-between items-center mb-6 border-b border-slate-800/50 pb-4">
              <h2 className="text-xl font-bold text-white flex items-center gap-2">
                Contact & Social Hub
              </h2>
              <button
                onClick={() =>
                  isEditingSocials
                    ? handleSaveSocials()
                    : setIsEditingSocials(true)
                }
                className="text-sm flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-700 text-slate-300 hover:text-white hover:bg-slate-800 transition"
              >
                {isEditingSocials ? (
                  <>
                    <Save className="w-4 h-4 text-emerald-400" /> Save Details
                  </>
                ) : (
                  <>
                    <Edit3 className="w-4 h-4" /> Edit Details
                  </>
                )}
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="flex items-center gap-3 bg-slate-900/80 p-3 rounded-lg border border-slate-800">
                <div className="bg-rose-500/10 p-2 rounded-lg">
                  <Mail className="w-5 h-5 text-rose-400" />
                </div>
                {isEditingSocials ? (
                  <input
                    type="email"
                    value={socials.email}
                    onChange={(e) =>
                      setSocials({ ...socials, email: e.target.value })
                    }
                    className="bg-transparent outline-none text-white text-sm w-full"
                    placeholder="Email Address"
                  />
                ) : (
                  <a
                    href={`mailto:${socials.email}`}
                    className="text-sm text-slate-300 truncate hover:text-rose-400 transition"
                  >
                    {socials.email || "Not provided"}
                  </a>
                )}
              </div>

              <div className="flex items-center gap-3 bg-slate-900/80 p-3 rounded-lg border border-slate-800">
                <div className="bg-blue-500/10 p-2 rounded-lg">
                  <Linkedin className="w-5 h-5 text-blue-500" />
                </div>
                {isEditingSocials ? (
                  <input
                    type="text"
                    value={socials.linkedin}
                    onChange={(e) =>
                      setSocials({ ...socials, linkedin: e.target.value })
                    }
                    className="bg-transparent outline-none text-white text-sm w-full"
                    placeholder="LinkedIn URL"
                  />
                ) : (
                  <a
                    href={formatUrl(socials.linkedin)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm text-slate-300 truncate hover:text-blue-400 transition"
                  >
                    {socials.linkedin || "Not provided"}
                  </a>
                )}
              </div>

              <div className="flex items-center gap-3 bg-slate-900/80 p-3 rounded-lg border border-slate-800">
                <div className="bg-sky-500/10 p-2 rounded-lg">
                  <Twitter className="w-5 h-5 text-sky-400" />
                </div>
                {isEditingSocials ? (
                  <input
                    type="text"
                    value={socials.twitter}
                    onChange={(e) =>
                      setSocials({ ...socials, twitter: e.target.value })
                    }
                    className="bg-transparent outline-none text-white text-sm w-full"
                    placeholder="Twitter URL"
                  />
                ) : (
                  <a
                    href={formatUrl(socials.twitter)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm text-slate-300 truncate hover:text-sky-400 transition"
                  >
                    {socials.twitter || "Not provided"}
                  </a>
                )}
              </div>

              <div className="flex items-center gap-3 bg-slate-900/80 p-3 rounded-lg border border-slate-800">
                <div className="bg-emerald-500/10 p-2 rounded-lg">
                  <Phone className="w-5 h-5 text-emerald-500" />
                </div>
                {isEditingSocials ? (
                  <input
                    type="text"
                    value={socials.whatsapp}
                    onChange={(e) =>
                      setSocials({ ...socials, whatsapp: e.target.value })
                    }
                    className="bg-transparent outline-none text-white text-sm w-full"
                    placeholder="WhatsApp Number"
                  />
                ) : (
                  <a
                    href={`https://wa.me/${socials.whatsapp?.replace(/[^0-9]/g, "")}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm text-slate-300 truncate hover:text-emerald-400 transition"
                  >
                    {socials.whatsapp || "Not provided"}
                  </a>
                )}
              </div>
            </div>
          </Card>

          {!isGraded ? (
            <Card className="p-8 border-amber-500/20 bg-amber-500/5 flex flex-col items-center text-center">
              <div className="w-16 h-16 bg-amber-500/20 rounded-full flex items-center justify-center mb-6 animate-pulse">
                <Clock className="w-8 h-8 text-amber-500" />
              </div>
              <h2 className="text-2xl font-bold text-white mb-2">
                Assessment Under Review
              </h2>
              <p className="text-slate-400 max-w-md leading-relaxed">
                Your final projects and exams are currently being evaluated by
                the hub managers. Your performance score will appear here once
                grading is complete.
              </p>
            </Card>
          ) : (
            <Card className="p-8 border-emerald-500/20 bg-emerald-500/5 relative overflow-hidden">
              <div className="absolute -top-10 -right-10 w-40 h-40 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none"></div>

              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8 border-b border-slate-800/50 pb-6 relative z-10">
                <div>
                  <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                    <CheckCircle2 className="w-6 h-6 text-emerald-500" />{" "}
                    Official Results
                  </h2>
                  <p className="text-slate-400 mt-1">
                    Your verified grading breakdown.
                  </p>
                </div>
                <PerformanceBadge score={student.finalPerformanceScore} />
              </div>

              <div className="space-y-4 relative z-10">
                <div className="bg-slate-900/80 p-5 rounded-xl border border-slate-800 flex justify-between items-center">
                  <p className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-1">
                    Final Exam (40%)
                  </p>
                  <p className="text-2xl font-black text-white">
                    {student.examScore}
                    <span className="text-slate-500 text-lg">/100</span>
                  </p>
                </div>
                <div className="bg-slate-900/80 p-5 rounded-xl border border-slate-800 flex justify-between items-center">
                  <p className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-1">
                    Projects (30%)
                  </p>
                  <p className="text-2xl font-black text-white">
                    {student.assignmentScore}
                    <span className="text-slate-500 text-lg">/100</span>
                  </p>
                </div>
                <div className="bg-slate-900/80 p-5 rounded-xl border border-slate-800 flex justify-between items-center">
                  <p className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-1">
                    Soft Skills (30%)
                  </p>
                  <p className="text-2xl font-black text-white">
                    {student.behaviorScore}
                    <span className="text-slate-500 text-lg">/100</span>
                  </p>
                </div>
              </div>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
